package tls13

import (
	"encoding/binary"
	"errors"
	"io"
)

type ContentType byte
type State int
type RecordVersion string

const (
	ChangeCipherSpec     ContentType = ContentType(20)
	Alert                ContentType = ContentType(21)
	ContentTypeHandshake ContentType = ContentType(22)
	ApplicationData      ContentType = ContentType(23)

	TLS13 RecordVersion = "\x03\x04"

	Initialized     State = 0
	ContentTypeDone State = 1
	VersionDone     State = 2
	LengthDone      State = 3
	Complete        State = 4
)

type TLSPlainText struct {
	ContentType     ContentType
	ProtocolVersion RecordVersion
	length          uint16
	fragment        []byte
	state           State
}

func (r *TLSPlainText) parseSingle(data []byte) (int, error) {
	// based on current state of request, handle next step
	switch r.state {

	case Initialized:
		if len(data) < 1 {
			return 0, errors.New("Not enough data to parse ContentType")
		}

		// parse ContentType which is 1 byte
		contentType := ContentType(data[0])
		if contentType != ChangeCipherSpec && contentType != Alert && contentType != ContentTypeHandshake && contentType != ApplicationData {
			return 0, errors.New("Invalid ContentType")
		}

		r.ContentType = contentType
		r.state = ContentTypeDone
		return 1, nil

	case ContentTypeDone:
		// parse legacyVersion
		// MUST be set to 0x0303 for all records
		// generated by a TLS 1.3 implementation other than an initial
		// ClientHello (i.e., one not generated after a HelloRetryRequest),
		// where it MAY also be 0x0301 for compatibility purposes
		if len(data) < 2 {
			return 0, errors.New("Not enough data to parse Version")
		}

		version := RecordVersion(string(data[0:2]))
		if version != TLS13 {
			return 0, errors.New("Version not supported")
		}

		r.ProtocolVersion = version
		r.state = VersionDone
		return 2, nil

	case VersionDone:
		// parse content length
		if len(data) < 2 {
			return 0, errors.New("Not enough data to parse length")
		}

		size := binary.BigEndian.Uint16(data[0:2])
		if size > (1 << 14) {
			return 0, errors.New("record_overflow: Size cannot be greater than 2^14.")
		}

		r.length = size
		r.state = LengthDone
		return 2, nil
	case LengthDone:
		// parse fragment contents
		if len(data)+len(r.fragment) > int(r.length) {
			return 0, errors.New("Size of data is greater than specified length")
		}

		r.fragment = append(r.fragment, data...)

		if len(r.fragment) == int(r.length) {
			r.state = Complete
			return len(data), nil
		}

		return len(data), nil
	}

	return 0, nil
}

func (record *TLSPlainText) parse(data []byte) (int, error) {
	// because our current chunk can have multiple parts of the request
	// (both request line and headers for ex)
	// run the loop until either the entire request is parsed or all bytes are consumed
	bytesParsed := 0
	for record.state != Complete {
		// RFC 8446 D.4: the client isn't actually changing cipher specs, it's just sending a legacy signal to confuse intermediaries that expect TLS 1.2. Must silently discard these records.
		if record.state == ContentTypeDone && record.ContentType == ChangeCipherSpec {
			continue
		}

		n, err := record.parseSingle(data[bytesParsed:])
		if err != nil {
			return bytesParsed, err
		}

		if n == 0 {
			return bytesParsed, nil
		}

		bytesParsed += n
	}

	return bytesParsed, nil
}

/**
* Read TLS record, structure of TLS record:
* ContentType (1) | LegacyVersion (2) | Length (2) | Fragment (variable)
 */
func readRecord(r io.Reader) (contentType ContentType, data []byte, err error) {
	buf := make([]byte, 8)
	var tlsRecord TLSPlainText
	var line string
	var bytesRead int
	var bytesParsed int

	for {
		if tlsRecord.state == Complete {
			return tlsRecord.ContentType, tlsRecord.fragment, nil
		}

		// if there is a request in flight read more bytes
		n, err := r.Read(buf)
		if err != nil {
			return 0, nil, errors.New("Error reading data")
		}

		line += string(buf[:n])
		bytesRead += n

		// received some amount of text
		bytes, err := tlsRecord.parse([]byte(line))
		if err != nil {
			return 0, nil, err
		}

		// after parsing set line to the remainder of parts
		bytesParsed += bytes
		line = line[bytes:]
	}
}

func writeRecord(w io.Writer, contentType ContentType, data []byte) error {
	var res []byte
	res = append(res, byte(contentType))
	res = append(res, TLS13...)

	size := make([]byte, 2)
	binary.BigEndian.PutUint16(size, uint16(len(data)))

	res = append(res, size...)
	res = append(res, data...)

	_, err := w.Write(res)
	return err
}
